apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-verify
  namespace: oauth2-proxy
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local:4180/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Set-Cookie
      - Authorization
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-signin
  namespace: oauth2-proxy
spec:
  errors:
    status:
      - "401"
    service:
      name: oauth2-proxy
      port: 4180
    query: "/oauth2/sign_in?rd={url}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth
  namespace: oauth2-proxy
spec:
  chain:
    middlewares:
      - name: oauth-verify
      - name: oauth-signin
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-only
  namespace: kube-system
spec:
  ipAllowList:
    sourceRange:
      - 192.168.0.0/16
      - 10.0.0.0/8