apiVersion: v1
kind: ConfigMap
metadata:
    name: oauth2-proxy-config
    namespace: oauth2-proxy
data:
    #ENC[AES256_GCM,data:nIcJQwHaVqun9V1WIPw=,iv:liABoC28B0C4XjykUTshrLPqK2Lcbz8ZX7PPamgqKKM=,tag:njsQLURECB0pISTjGytT/Q==,type:comment]
    oauth2-proxy.cfg: ENC[AES256_GCM,data:62OuSlR6HDgWCJ/Zt8bty5DwK616GdT1ZBFF5qsqgAAmNpkJIPMfURFLuHnZ5ZQxcU3tVN9G9UahuPjFUC08UCcIq7/QkC7w2QCr52Nc/YYnHOlZBqVchll0RVdKrr8P4DW+NqnWOHjs+kH+I+6BL9J4Jmb6qr6GF6M+0PSe8jvNA3LznYzGecT/2V9Gai6+MiTI8HTTGVidWBAmVkJi8ePD+8iXn862mljC18AR7k/2RieVzGWuOk8S+MlcmR/3gNsyGzFPqNvklnyvDzistJQe57ARI9r6l1piqlxQjIN12aFDcqhHnXYGD+XYOIU6cF7PdOIaq4cRHDp5jxrERlyGCj1WQcGKsioDr2czvKarNwxrX1StY38ntYFbwlBdvfgfiDF36ojG3elxm0qYCh581e6/gYINDSq3eJDwHmO6yI7BnEWyuCgpcAU0dpD1WuFltldHbd6sv2hO73IMJr0yMKOciAbX+kq9Z62YlrjF7CLCSEPT7fexl8rudJCehN7VBLMDWHT9OV/Sj5wpp8eoJDlObMwccoY64JE4/Y//XxHYkCxH2FWWmYUSZQtsbVNDzO6yf+tkjwNnwVO3pCe8zDBg2wFBwom9bFp2y0DDWhyYaTY/8rJRPrg4AwmC6Jys7hQelqhswJxsWk+Boca4OQcrp2a/+0qA8q9wu8eVFRy3D/zUlStD673slTmcIwRDeoopObcxoBgTWSj7zmNK6ENrX9zYD3G6HutL7dGQP7zfLJ+LX7o7XMKqOfWf031WRsmdn8GhoGZ4VQ94BtL7ZRcjCA/Uvg3uCKJOFt0xDHscVYPqiBCCfvPDR8l5Y9t+f808JSsIlKTG8MlIatxNEUtMddMCCGKc6j3ctTs2+aNkGqfkw4CA6ZALREmds9mUhKGnlrG2u5JYdrhxX9oGZ0Tjp8cosCDFbCdXBWeS2kTQVMTT5xe7ullOjJE6G1av6NyIiKBVVev5bBd6WRxtzIT+aG7UvWbm2hzzb+WFMGm6Bhdte3wpBR0d5uol3h9Ma8RpXfruB4pXTH/kEa8r4IcRaMYirO0hpg==,iv:TiVqWtXN7JB9XH2SKfj/6aX8l4yDcGMjApbWu5lJbw8=,tag:ya8TjT7xLNZLqcCBd01uXA==,type:str]
    authenticated_emails.cfg: ENC[AES256_GCM,data:P9HLSFzP6OyNgyWVtCxZBEllfi+zcU28OCBxgS0eI5LKFVogy84lcfYaWhMkKyjqw2Y+zy0ftVo6,iv:No1MB4VUCMpbiq4DddTkR0uHj2jSXG//Yezmi6URq0M=,tag:ZjleiGY+w/iCRuQ5PXek7g==,type:str]
sops:
    age:
        - recipient: age1099kpzqp5v429mcyekxxnnyfkyuqxgq3esxvamc0kv7tf7nh9g9qymcpmx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSEJLNDZBWklJWkprRUNH
            UGNrQU1YRWRUeU5oam1XOHRCMlpiTzZlS0JFCjI3WHlmbjhaZEkzRFFKZnA5Sm9v
            T1VUbkZRUFZVUFhkUk55UTlCbDFENU0KLS0tIDExM2ZTKzJNektmU2c3VS95Mkhr
            eGh1ejNMbTJBUS9IMkJDYlFYZFF1Ym8KmtunSMvbuwLGDmK2fXJ5brxDdC0D2wEb
            mj/78+8LVJRwlp9w3URFYzlO3ecwQExj9bvfiR0/uiyfWSgmas2oBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T21:22:16Z"
    mac: ENC[AES256_GCM,data:0OhP/keJaa1Ki/MF/6iFDSDAu/OKIyfXyK+CIc2BPXa4yoA5acjl0qQM1vzVe5gWhFt/6eFwUvfr4Xo3BDnJqO7xzQRwFsZ8xncvaURzHMdt9uEa8/FHAF7Byv8yF3FS5bo+3fYNAHTaoMe2rrWQFUl4ocVcCbPeCwJ2vz7okxI=,iv:9TAeS9RgfARN9lyQvj9L8GPaAN7ou3rL6WidlXS6IX0=,tag:2vl27+c1W10D2x8E+NGvxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
